### ISSUE TITLE
Unstandardized language codes?

### ISSUE THREAD

**Issue by PlagaMedicum** [ostis-apps/ostis-linguistics#1]
I think that we need to define a standard, used for language codes.
Now we are using codes from different ISO's: ISO 639-1(en, ru) and ISO 639-2(chi).

**Comment by ShunkevichDV** [comment]
What is your suggestion?

**Comment by PlagaMedicum** [comment]
I think there is no sense to completely migrate from ISO 639-1, so i propose to follow ISO 639-1 and 639-3 for languages that is not present in 639-1 standard. This means that we need to change language code for chinese from "chi" to "zh".

**Comment by ShunkevichDV** [comment]
Rename and add to PR
