### ISSUE TITLE
Architecture of the project

### ISSUE THREAD

**Issue by PlagaMedicum** [ostis-apps/ostis-linguistics#3]
Here i want to discuss architecture of the project.

Let's start with questions like:
Which projects will be our references?
Do we need to separate sections, subject domains, relations and concepts? How?

**Comment by ShunkevichDV** [comment]
1. For now it is linguistics project knowledge base onle, so it may be cloned in empty OSTIS core and then built as part of knowledge base (even if agents will be added). We may make a specific repo with installation scripts and references to other OSTIS projects, but it should be another repo, not this, and I think it is not necessary now
2. Of course we need separate them, the best example for now is IMS KB repo:
https://github.com/ostis-dev/ims.ostis.kb/tree/master/ims/ostis_tech 
Subject domains were separated in my .doc sources, I think it is enought for now, so we need to separate concepts and describe subject domains

**Comment by PlagaMedicum** [comment]
For now i intend to make this kind of architecture:
```python
subsystem_of_languages
| objects
| | language
| | | src
| | | | html
| | | | img
| | | | ...
| | | language_natural
| | | | ...
| | | language_artificial
| | | | ...
| | | ... # Other subdividings and subclasses
| | | language.scs # Here we put all main information about concept(type of the node, idtfs, explanations, definitions etc)
| | | language.scsi # Here are all subdividings and other connections with objects.
| section_subjdomain_of_languages
| | section_subjdomain_of_natural_languages
| | | src
| | | | ...
| | | ... # Subsections
| | | section_subjdomain_of_natural_languages.scs
| | | subject_domain_of_natural_languages.scs
| | section_subjdomain_of_artificial_languages
| | | ...
| | ... # Subsections
| | section_subjdomain_of_languages.scs
| | subject_domain_of_languages.scs
| ...
| subsystem_of_languages.scs
subsystem_of_natural_language_texts
| objects
| | ...
| section_subjdomai_of_natural_language_texts
| | ...
| ...
| subbsystem_of_natural_language_texts.scs
...
ostis_linguistics_kb.scs
```

**Comment by ShunkevichDV** [comment]
Can't understand your idea, may be example file attaching will be better

**Comment by PlagaMedicum** [comment]
I tried to draw here a directory tree. Can't understand which file i can attach, a tree with better formatting?

If `.scs/.scsi` file uses some external files(except `.scs/.scsi`) we create `src` directory.
At the high level KB separate on a bunch of "subsystems".
Each "subsystem" contains:
* hi-level sections
* objects(concepts, rrels etc) in one separate directory
* other files and directories(justification, history etc)

Each section contains:
* `src` folder
* subsections
* related `.scs` files

Each object contains:
* it's `src` folder
* related `.scs`(all main information about the sc node(type, idtfs, explanations, definitions etc)) and `.scsi`(all subdividings and connections with other objects)
* objects that are on the lower lever for this object(subclasses and subdividings(?))

**Comment by ShunkevichDV** [comment]
Better to discuss tomorrow in university, I'll be from 11 to 13

**Comment by PlagaMedicum** [comment]
Ok
