### ISSUE TITLE
Work plans and project tasks

### ISSUE THREAD

**Issue by PlagaMedicum** [ostis-apps/ostis-linguistics#6]
Here we discuss future work on the project and posting upcoming tasks.

From today's meeting we have following:
1. Complete our classification of lexemes with exceptions from classification and A.Hardzei's articles. Use intersections of classes in special cases of classification. All necessary info can be found in docs on our project's  _Google Drive_.
2. Create agents of morphological analyze.
3. Create a test dictionary for agents.
4. Formalize paradigms of actions in _A.Hardzei "Theory for automatic generation of knowledge architecture: TAPAZ-2"_ book.

Additional tasks:
1. Create agent of syntactical analyze.
2. Formalize grammatical categories.
3. Still need to fix some terminology.

**Comment by ShunkevichDV** [comment]
It is quite good, but there are Issues for tasks, not necessary to store task lists in one Issue

**Comment by PlagaMedicum** [comment]
Hmm, reasonable. Of course, separate issues will be created if there will be need to.

**Comment by ShunkevichDV** [comment]
I insist on it, it is bad practice to have text issues list when there is enough powerful tools for it

**Comment by PlagaMedicum** [comment]
So you suggest to create 7 new issues now?
